### ISSUE TITLE
После коррекциях на растрах слишком много значений "1"

### ISSUE THREAD

**Issue by AlexeyPechnikov** [oldbay/raster_tools#1]
Процессинг создает большие области с единственным значением "1". Вероятно, неправильно определяется максимальное значение исходного растра.

**Comment by AlexeyPechnikov** [comment]
Пример для сцены Ландсат 8: LC80900892016133LGN00 (landsat8_const_esun в конфиге не меняет результат).

Исходный канал 5:
![before](https://user-images.githubusercontent.com/7342379/33229183-35a28dce-d1fc-11e7-9866-22cd0f578342.png)

Результирующий канал nir:
![after](https://user-images.githubusercontent.com/7342379/33229182-35376ab2-d1fc-11e7-9781-76f931b2e691.png)

**Comment by AlexeyPechnikov** [comment]
Смотрим LC80900892016133LGN00_MTL.txt:
    REFLECTANCE_MAXIMUM_BAND_5 = 1.210700
    REFLECTANCE_MINIMUM_BAND_5 = -0.099980

И проверим, что получилось на выходе:
gdalinfo -stats nir.tif
...
    STATISTICS_MAXIMUM=1
...
    STATISTICS_MINIMUM=-1.3098787069321

Максимальное значение "1" некорректно.

**Comment by oldbay** [comment]
Добрый день.
Ошибку подтверждаю. Исправил в версии 0.3 (commit 4d090e8)
п.с:
Версия 0.3 скорее всего последняя для общего проекта rastre_tools и raster_calc, к 0.4 версии проекты будут разделены.
